### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hranicky** [satwikkansal/python_blockchain_app#50]
Press butto POST generates:
Traceback (most recent call last):
  File "c:\pf_c\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\pf_c\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\pf_c\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\pf_c\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\pf_c\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\pf_c\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "F:\Alexandria\Devel\GITRepoWork\python_blockchain_app\app\views.py", line 64, in submit_textarea
    requests.post(new_tx_address,
  File "c:\pf_c\python38\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "c:\pf_c\python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\pf_c\python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\pf_c\python38\lib\site-packages\requests\sessions.py", line 685, in send
    r.content
  File "c:\pf_c\python38\lib\site-packages\requests\models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "c:\pf_c\python38\lib\site-packages\requests\models.py", line 754, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
127.0.0.1 - - [29/Nov/2020 19:09:24] "←[35m←[1mPOST /submit HTTP/1.1←[0m" 500 -
Thanks for Your info appl734e@gmail.com

**Comment by satwikkansal** [comment]
It's highly likely that node servers haven't been started properly, please check your env variables.
